#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 17 16:18:14 2023

@author: prpa
"""



import time
import random
from multiprocessing import Lock, Condition, Process
from multiprocessing import Value

SOUTH = 1
NORTH = 0

NCARS = 10
NPED = 10
TIME_CARS = 0.5  # a new car enters each 0.5s
TIME_PED = 1 # a new pedestrian enters each 5s
TIME_IN_BRIDGE_CARS = (1, 0.5) # normal 1s, 0.5s
TIME_IN_BRIDGE_PEDESTRGIAN = (3, 1) # normal 1s, 0.5s

class Monitor():
    def __init__(self):
        self.mutex = Lock()
        self.patata = Value('i', 0)
        self.personas_dentro = Value('i', 0)
        self.coches_dentro = Value('i', 0)

        self.hay_coches = Condition(self.mutex)
        self.hay_personas = Condition(self.mutex)
        self.preferencia = 0
        self.hay_coches_esperando = Condition(self.mutex)

        self.hay_coches_esperando_norte = 0
        self.hay_coches_esperando_sur = 1

    def wants_enter_car(self, direction: int) -> None:
        self.mutex.acquire()
        self.patata.value += 1

        if direction == 0:
            self.hay_coches_esperando_norte += 1
            self.hay_personas.wait_for(self.no_hay_personas_dentro)
            self.hay_coches.wait_for(self.no_hay_coches_dentro)
            self.hay_coches_esperando.wait(self.preferencia == 0)
                        
            self.hay_coches_esperando_norte -= 1
            self.coches_dentro.value += 1


        else:
            self.hay_coches_esperando_sur += 1
            self.hay_personas.wait_for(self.no_hay_personas_dentro)
            self.hay_coches.wait_for(self.no_hay_coches_dentro)
            self.hay_coches_esperando.wait(self.preferencia == 1)
            self.hay_coches_esperando_sur -= 1
            self.coches_dentro.value += 1

            

        self.mutex.release()

    def leaves_car(self, direction: int) -> None:
        self.mutex.acquire() 
        self.patata.value += 1
        
        
        self.coches_dentro.value -= 1
        self.hay_coches.notify()
        
        if direction == 0:
            if self.hay_coches_esperando_sur > 0:
                self.preferencia = 1
        else:
            if self.hay_coches_esperando_norte > 0:
                self.preferencia = 0
    
        self.mutex.release()

    def wants_enter_pedestrian(self) -> None:
        self.mutex.acquire()
        self.patata.value += 1

        
        self.hay_coches.wait_for(self.no_hay_coches_dentro)
        self.personas_dentro.value += 1
        
        self.mutex.release()

    def leaves_pedestrian(self) -> None:
        self.mutex.acquire()
        self.patata.value += 1

        self.personas_dentro.value -= 1
        if self.personas_dentro.value == 0:
            self.hay_personas.notify()
    
        self.mutex.release()

    def no_hay_personas_dentro(self):
        return self.personas_dentro.value == 0
    
    def no_hay_coches_dentro(self):
        return self.coches_dentro.value == 0

    def __repr__(self) -> str:
        return f'Monitor: {self.patata.value}'

def delay_car_north() -> None:
    pass

def delay_car_south() -> None:
    pass

def delay_pedestrian() -> None:
    pass

def car(cid: int, direction: int, monitor: Monitor)  -> None:
    print(f"car {cid} heading {direction} wants to enter. {monitor}")
    monitor.wants_enter_car(direction)
    print(f"car {cid} heading {direction} enters the bridge. {monitor}")
    if direction==NORTH :
        delay_car_north()
    else:
        delay_car_south()
    print(f"car {cid} heading {direction} leaving the bridge. {monitor}")
    monitor.leaves_car(direction)
    print(f"car {cid} heading {direction} out of the bridge. {monitor}")

def pedestrian(pid: int, monitor: Monitor) -> None:
    print(f"pedestrian {pid} wants to enter. {monitor}")
    monitor.wants_enter_pedestrian()
    print(f"pedestrian {pid} enters the bridge. {monitor}")
    delay_pedestrian()
    print(f"pedestrian {pid} leaving the bridge. {monitor}")
    monitor.leaves_pedestrian()
    print(f"pedestrian {pid} out of the bridge. {monitor}")



def gen_pedestrian(monitor: Monitor) -> None:
    pid = 0
    plst = []
    for _ in range(NPED):
        pid += 1
        p = Process(target=pedestrian, args=(pid, monitor))
        p.start()
        plst.append(p)
        time.sleep(random.expovariate(1/TIME_PED))

    for p in plst:
        p.join()

def gen_cars(monitor) -> Monitor:
    cid = 0
    plst = []
    for _ in range(NCARS):
        direction = NORTH if random.randint(0,1)==1  else SOUTH
        cid += 1
        p = Process(target=car, args=(cid, direction, monitor))
        p.start()
        plst.append(p)
        time.sleep(random.expovariate(1/TIME_CARS))

    for p in plst:
        p.join()

def main():
    monitor = Monitor()
    gcars = Process(target=gen_cars, args=(monitor,))
    gped = Process(target=gen_pedestrian, args=(monitor,))
    gcars.start()
    gped.start()
    gcars.join()
    gped.join()


if __name__ == '__main__':
    main()
